<meta charset="UTF-8">
<title>Aegon</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="x-ua-compatible" content="ie=edge">

<!-- Open Graph Tags -->
<meta property="og:title" content="Aegon-title" />
<meta property="og:type" content="Website" />
<meta property="og:url" content="http://www.aegon.com/" />
<meta property="og:image" content="http://www.aegon.com/image.jpg" />
<meta property="og:description" content="Aegon-description" />
<meta property="og:site_name" content="Aegon" />

<!-- Twitter Summary Card -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@Aegon" />
<meta name="twitter:title" content="Aegon-title" />
<meta name="twitter:description" content="Aegon-description" />
<meta name="twitter:image" content="http://www.aegon.com/image.jpg" />

<!-- Favicons -->
<link rel="shortcut icon" type="image/x-icon" href="/img/favicon/favicon.ico">
<link rel="apple-touch-icon" sizes="180x180" href="/img/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/img/favicon/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/img/favicon/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/img/favicon/manifest.json">
<link rel="mask-icon" href="/img/favicon/safari-pinned-tab.svg" color="#0077c8">
<meta name="theme-color" content="#ffffff">

<!-- Preload Fonts -->
<link rel="preload" as="font" crossorigin="crossorigin" type="font/woff2" href="/fonts/2527EE_5_0.woff" />
<link rel="preload" as="font" crossorigin="crossorigin" type="font/woff2" href="/fonts/2527EE_3_0.woff" />
<link rel="preload" as="font" crossorigin="crossorigin" type="font/woff2" href="/fonts/2527EE_2_0.woff" />
<link rel="preload" as="font" crossorigin="crossorigin" type="font/woff2" href="/fonts/2527EE_A_0.woff" />
<link rel="preload" as="font" crossorigin="crossorigin" type="font/woff2" href="/fonts/2527EE_0_0.woff" />
<link rel="preload" as="font" crossorigin="crossorigin" type="font/woff2" href="/fonts/2527EE_9_0.woff" />

<!-- Styles -->
<link href="/css/main.css" rel="stylesheet">
