<script src="/js/bundle.js"></script>

<script type="text/javascript">
    var addthisScript = document.createElement('script');
        addthisScript.setAttribute('src', '//s7.addthis.com/js/300/addthis_widget.js#domready=1')
        document.body.appendChild(addthisScript)

        var addthis_config = addthis_config || {};
            addthis_config.pubid = 'ra-58caa647ce1ddcf9';
</script>

<!-- <script async defer src="https://api-uk18.kurtosys.io/tools/ksys394/static/ksys394_tools_staging.js"></script> -->
