<footer role="contentinfo" class="footer">

    <div class="container">

        <div class="doormat-nav">

            <div class="doormat-nav__list">
                <h3 class="doormat-nav__heading"><a href="">About us</a></h3>
                <ul class="doormat-nav__items">
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                </ul>
            </div>

            <div class="doormat-nav__list">
                <h3 class="doormat-nav__heading"><a href="">Aegon & Society</a></h3>
                <ul class="doormat-nav__items">
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                </ul>
            </div>

            <div class="doormat-nav__list">
                <h3 class="doormat-nav__heading"><a href="">Investors</a></h3>
                <ul class="doormat-nav__items">
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                </ul>
            </div>

            <div class="doormat-nav__list">
                <h3 class="doormat-nav__heading"><a href="">Newsroom</a></h3>
                <ul class="doormat-nav__items">
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                </ul>
            </div>

            <div class="doormat-nav__list">
                <h3 class="doormat-nav__heading"><a href="">Careers</a></h3>
                <ul class="doormat-nav__items">
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                    <li class="doormat-nav__item">
                        <a href="">Item text</a>
                    </li>
                </ul>
            </div>

        </div>

        <div class="footer-bar">

            <div class="footer-bar__logo">
                <a href="/">
                    <div class="svg-container">
                        <svg role="img" title="Aegon">
                           <use xlink:href="../img/img.svg#icon-aegon-logo"></use>
                        </svg>
                    </div>
                </a>
            </div>

            <div class="footer-bar__social-links">
                <a href="" class="footer-bar__social-links__facebook">
                    <div class="svg-container">
                        <svg role="img" title="Facebook">
                           <use xlink:href="../img/img.svg#icon-facebook"></use>
                        </svg>
                    </div>
                </a>
                <a href="" class="footer-bar__social-links__twitter">
                    <div class="svg-container">
                        <svg role="img" title="Twitter">
                           <use xlink:href="../img/img.svg#icon-twitter"></use>
                        </svg>
                    </div>
                </a>
                <a href="" class="footer-bar__social-links__linkedin">
                    <div class="svg-container">
                        <svg role="img" title="Linkedin">
                           <use xlink:href="../img/img.svg#icon-linkedin"></use>
                        </svg>
                    </div>
                </a>
                <a href="" class="footer-bar__social-links__slideshare">
                    <div class="svg-container">
                        <svg role="img" title="SlideShare">
                           <use xlink:href="../img/img.svg#icon-slideshare"></use>
                        </svg>
                    </div>
                </a>
                <a href="" class="footer-bar__social-links__youtube">
                    <div class="svg-container">
                        <svg role="img" title="SlideShare">
                           <use xlink:href="../img/img.svg#icon-youtube"></use>
                        </svg>
                    </div>
                </a>
                <a href="" class="footer-bar__social-links__google">
                    <div class="svg-container">
                        <svg role="img" title="Google+">
                           <use xlink:href="../img/img.svg#icon-google+"></use>
                        </svg>
                    </div>
                </a>
            </div>

        </div>

        <div class="foot">
            <div class="foot__meta-links">
                <ul class="foot__meta-links__items">
                    <li class="foot__meta-links__item"><a href="">Legal</a></li>
                    <li class="foot__meta-links__item"><a href="">Privacy & Cookies</a></li>
                    <li class="foot__meta-links__item"><a href="">Regulatory</a></li>
                    <li class="foot__meta-links__item"><a href="">Sitemap</a></li>
                    <li class="foot__meta-links__item"><a href="">Accessibility</a></li>
                </ul>
            </div>

            <div class="foot__copyright">
                <span>&copy; Aegon 2017</span>
            </div>
        </div>

    </div>

</footer>
